title: Wanli's Blog
subtitle: A Technology Blog built for Graphics Developers
description: >- # this means to ignore newlines until "baseurl:"
  A Technology Blog built for Graphics Developers
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wanlizhu.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: Wanli ZHU  #for comments using disqus
author: Wanli ZHU
author_bio: This is a technology built for graphics developers. Anyone can read and post their ideas to a blog like this. As easy as PIE !
author_email: "sinoxavier@outlook.com"
author_location: China
author_website_url: "https://wanlizhu.github.io"

# social links
twitter_username: wanlizhu
github_username:  wanlizhu
facebook_username: wanlizhu
linkedin_username: wanlizhu
behance_username: wanlizhu
instagram_username: wanlizhu
medium_username: wanlizhu
telegram_username: wanlizhu
dribbble_username: wanlizhu 
flickr_username: wanlizhu

# dont touch this unless required
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics
  - jekyll-algolia
  - jekyll-menus 


# code highlighter
highlighter: rouge

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-145139169-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# minify html
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

